roles: ["agent", "scanner", "watcher"]
log_level: "debug"
log_dir: "/tmp/managerd"
watcher:
  interval: 60 sec
  mode: thread
scanner:
  targets: ["192.168.19.0/24","10.0.0.0/24"]
  interval: 2 mins
  directory: "/opt/dynamite/scans"
  exclusions: ["192.168.19.36"]
